language: php

php:
  - 7.0
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty

install:
  - composer install
