language: php

php:
  - 5.5
  - 7.0
  - 7.4

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty

install: 

script:
  - composer require phpunit/phpunit --update-no-dev
  - composer test
