language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - COVERALLS_PARALLEL=true
    - COMPOSER_MEMORY_LIMIT=-1

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty

install: composer install

after_success: php vendor/bin/php-coveralls -x clover.xml -v

notifications:
  webhooks: https://coveralls.io/webhook
