language: php

os:
  - linux
  - osx

php:
  - 7.3
  - 7.4

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty

install: composer require phpunit/phpunit --no-update

script: composer test
