language: php

php:
  - 5.6
  - 7.4

jobs:
  include:
    - php: 5.3
      dist: precise
      install: composer dump-autoload --no-dev
      script: phpunit
    - php: 5.4
      dist: trusty
      install: composer dump-autoload --no-dev
      script: phpunit
    - php: 5.5
      dist: trusty
      install: composer dump-autoload --no-dev
      script: phpunit

install: composer install

script: composer test
