language: php

php:
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - COVERALLS_PARALLEL=true

jobs:
  include:
    - php: 5.3
      dist: precise
      after_success: echo 'ok'
    - php: 5.5
      dist: trusty

install: composer install

after_success: php vendor/bin/php-coveralls -v

notifications:
  webhooks: https://coveralls.io/webhook
